<a href="https://colab.research.google.com/github/19pa1a0209/AI-lab/blob/master/Experiment_1_Numpy's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment No1:Numpy

1)Different ways to create a Numpy arrays.

In [ ]:
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
y = np.array([[4,5,6],[7,8,9]])
print(y)

[[4 5 6]
 [7 8 9]]


2) Add,remove,modify elements in an array.

#Add

In [ ]:
b = np.append(y,[6,4,2])
print(b)

[4 5 6 7 8 9 6 4 2]


#remove

In [ ]:
newarray = np.delete(x,2)
print(newarray)

[1 2]


#modify

In [ ]:
b = np.array([6,4,1,3,5,9])
b[b<2] = -1
print(b)

[ 6  4 -1  3  5  9]


3)Arthematic operations on Numpy array.

In [2]:
import numpy as np
s = np.array([[4,4,4],[4,4,4]])
r = np.array([[4,4,4],[4,4,4]])#creates 2d arrays
sum = np.add(s,r)#adds the elements in two arrays
diff = np.subtract(s,r)#subtracts the elements in two arrays 
prod = np.multiply(s,r)#multiply the elements in the two arrays
quo = np.divide(s,r)#divides the elements in the two arrays
mod = np.mod(s,r)#it gives the remainder of the elements in two arrays
pow = np.power(s,r)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[8 8 8]
 [8 8 8]]
[[0 0 0]
 [0 0 0]]
[[16 16 16]
 [16 16 16]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]
[[256 256 256]
 [256 256 256]]


4)Slicing and iterating of numpy arrays.

#Slicing

In [ ]:
import numpy as np
arrays = np.array([1,2,3,4,5,6,7])
print(arrays[2:4])

[3 4]


#iterating

In [ ]:
for y in arrays:
  print(y)

1
2
3
4
5
6
7


5)Matrix operation on numpy arrays.

In [ ]:
import numpy as np
a = np.array([[3,4],[1,2]])
b = np.array([[7,8],[5,6]])
print(np.add(a,b))
print(np.divide(a,b))

[[10 12]
 [ 6  8]]
[[0.42857143 0.5       ]
 [0.2        0.33333333]]
